# Site settings
title: David Hern치ndez
url: 'http://davidhernandez.info/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'David Hern치ndez'
  email: hello@davidhernandez.info
  twitter_username: david_baltha
  github_username:  DavidHernandez
  linkedin_username:  davidhernandezruiz1

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

t:
  en:
    description: 'Software development - Training - Agile'
    services: 'Services'
    back: '<- Go back'
  es:
    description: 'Desarrollo de software - Formaci칩n - Agile'
    services: 'Servicios'
    back: '<- Volver atr치s'

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
